@base = https://ehtagconnector.azurewebsites.net
# @base = https://localhost:5001

### 查询数据库基本情况
GET {{base}}/api/database
Accept: application/json
If-None-Match: "5bd33aed633b18d5bca6b2d8c66dcf6b56bd75b1"

### 查询数据库数据版本
HEAD {{base}}/api/database
Accept: application/json
If-None-Match: "5bd33aed633b18d5bca6b2d8c66dcf6b56bd75b1"

### 查询某一分类的信息
GET {{base}}/api/database/reclass
Accept: application/json

### 查询某一条目是否存在
HEAD {{base}}/api/database/reclass/private

### 查询某一条目的翻译
GET {{base}}/api/database/male/shotacon?format=raw.json
Accept: application/json

### 增加条目
POST {{base}}/api/database/parody/gotoubun%20no%20hanayome
X-Token: e9b35fc3cd731c11d4e535724b1e376bfc2b3104
If-Match: "5bd33aed633b18d5bca6b2d8c66dcf6b56bd75b1"
Content-Type: application/json
Accept: application/html+json

{
    "name": "五等分的新娘",
    "intro": "《五等分的新娘》（日语：五等分の花嫁）是由日本漫画家春场葱所创作的少年漫画作品。于《周刊少年Magazine》2017年第36・37合并号开始正式连载中。 ",
    "links": "[维基百科](https://zh.wikipedia.org/zh-cn/五等分的新娘) (*)"
}

### 修改条目
PUT {{base}}/api/database/reclass/private
X-Token: e9b35fc3cd731c11d4e535724b1e376bfc2b3104
Content-Type: application/json
If-Match: "d4553b638098466ef013567b319c034f8ee34950"

{
  "name": "私人的",
  "intro": "私人画廊是一个非正式的类别，允许用户不与 E-Hentai 社区其他成员分享他们的内容。他们往往是想要成为自己的个人用户画廊，他们只是希望自己的朋友前来参观。",
  "links": ""
}

### 删除条目
DELETE {{base}}/api/database/reclass/private
X-Token: e9b35fc3cd731c11d4e535724b1e376bfc2b3104
If-Match: "3b24693f057ccb422ce76a3334be549c66139309"

### 格式化条目
POST {{base}}/api/tools/normalize?format=ast.json
Content-Type: application/json

{
    "name": "五等分的新娘",
    "intro": "《五等分的新娘》（日语：五等分の花嫁）是由日本漫画家春场葱所创作的少年漫画作品。于《周刊少年Magazine》2017年第36・37合并号开始正式连载中。 ",
    "links": "[维基百科](https://zh.wikipedia.org/zh-cn/五等分的新娘) (*)"
}